/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: [
    "./App.tsx",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require("nativewind/preset")],
  darkMode: 'class', // Enable class-based dark mode
  theme: {
    extend: {
      colors: {
        // Light theme colors
        light: {
          background: '#f8fafc',
          surface: '#ffffff',
          surfaceSecondary: '#f1f5f9',
          surfaceTertiary: '#e2e8f0',
          text: '#1e293b',
          textSecondary: '#64748b',
          textTertiary: '#94a3b8',
          textInverse: '#ffffff',
          primary: '#3b82f6',
          primaryLight: '#60a5fa',
          primaryDark: '#2563eb',
          secondary: '#10b981',
          secondaryLight: '#34d399',
          secondaryDark: '#059669',
          success: '#10b981',
          successLight: '#d1fae5',
          warning: '#f59e0b',
          warningLight: '#fef3c7',
          error: '#ef4444',
          errorLight: '#fee2e2',
          info: '#3b82f6',
          infoLight: '#dbeafe',
          border: '#e2e8f0',
          borderLight: '#f1f5f9',
          borderDark: '#cbd5e1',
          card: '#ffffff',
          cardBorder: '#e2e8f0',
          input: '#ffffff',
          inputBorder: '#d1d5db',
          inputFocus: '#3b82f6',
          inputPlaceholder: '#9ca3af',
          buttonPrimary: '#3b82f6',
          buttonPrimaryText: '#ffffff',
          buttonSecondary: '#f1f5f9',
          buttonSecondaryText: '#374151',
          buttonDanger: '#ef4444',
          buttonDangerText: '#ffffff',
          tabActive: '#3b82f6',
          tabInactive: '#64748b',
          tabBackground: '#ffffff',
        },
        // Dark theme colors
        dark: {
          background: '#0f172a',
          surface: '#1e293b',
          surfaceSecondary: '#334155',
          surfaceTertiary: '#475569',
          text: '#f8fafc',
          textSecondary: '#cbd5e1',
          textTertiary: '#94a3b8',
          textInverse: '#0f172a',
          primary: '#60a5fa',
          primaryLight: '#93c5fd',
          primaryDark: '#3b82f6',
          secondary: '#34d399',
          secondaryLight: '#6ee7b7',
          secondaryDark: '#10b981',
          success: '#34d399',
          successLight: '#064e3b',
          warning: '#fbbf24',
          warningLight: '#451a03',
          error: '#f87171',
          errorLight: '#7f1d1d',
          info: '#60a5fa',
          infoLight: '#1e3a8a',
          border: '#334155',
          borderLight: '#475569',
          borderDark: '#1e293b',
          card: '#1e293b',
          cardBorder: '#334155',
          input: '#334155',
          inputBorder: '#475569',
          inputFocus: '#60a5fa',
          inputPlaceholder: '#64748b',
          buttonPrimary: '#60a5fa',
          buttonPrimaryText: '#0f172a',
          buttonSecondary: '#334155',
          buttonSecondaryText: '#f8fafc',
          buttonDanger: '#f87171',
          buttonDangerText: '#0f172a',
          tabActive: '#60a5fa',
          tabInactive: '#94a3b8',
          tabBackground: '#1e293b',
        },
      },
      // Custom shadow configurations
      boxShadow: {
        'theme': '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
        'theme-lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'theme-dark': '0 1px 3px 0 rgba(0, 0, 0, 0.3), 0 1px 2px 0 rgba(0, 0, 0, 0.2)',
        'theme-dark-lg': '0 10px 15px -3px rgba(0, 0, 0, 0.3), 0 4px 6px -2px rgba(0, 0, 0, 0.2)',
      },
    },
  },
  plugins: [],
}